export const cards = {
  Maharashtra: {
    id: "state-1",
    heading: "Maharashtra",
    para: "Maharashtras capital, Mumbai (formerly Bombay),<br> is an island city on the western coast, connected<br> to the mainland by roads and railways.<br> Aptly called the gateway of India, Maharashtra is one<br> of India’s biggest commercial and industrial centres,<br> and it has played a significant role in the country’s<br> social and political life.",
    back_image:
      "linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.8)),url(Images/maharashtra.jpg)",
    card_image: "url(Images/maharashtra.jpg)",
  },
  Telangana: {
    id: "state-2",
    heading: "Telangana",
    para: "Telangana is situated largely in an upland region of the<br> Deccan (peninsular India). Much of its surface area<br> is occupied by the Telangana Plateau in the north<br> and the Golconda Plateau in the south and is composed<br> of gneissic rock (gneiss being a foliated rock formed<br> within Earth’s interior under conditions of heat<br> and pressure). ",
    back_image:
      "linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.8)),url(Images/telangana.jpg)",
    card_image: "url(Images/telangana.jpg)",
  },
  AndhraPradesh: {
    id: "state-3",
    heading: "Andhra Pradesh",
    para: "The state draws its name from the Andhra people,<br> who have inhabited the area since antiquity<br> and developed their own language, Telugu.<br> Andhra Pradesh came into existence in its present form<br> in 1956 as a result of the demand of the Andhras<br> for a separate state.",
    back_image:
      "linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.8)),url(Images/andhrapradesh.jpg)",
    card_image: "url(Images/andhrapradesh.jpg)",
  },
  Karnataka: {
    id: "state-4",
    heading: "Karnataka",
    para: "Before the independence of India in 1947,<br> Mysore was a prosperous and progressive but landlocked<br> princely state, with an area of less than 30,000 square<br> miles (78,000 square km), located on the<br> Karnataka Plateau. ",
    back_image:
      "linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.8)),url(Images/karnataka.jpg)",
    card_image: "url(Images/karnataka.jpg)",
  },
  Kerala: {
    id: "state-5",
    heading: "Kerala",
    para: "Although isolated from the Indian interior by the<br> mountainous belt of the Western Ghats,<br> Kerala has been exposed to many foreign influences<br> via its long coastline;<br> Consequently, the state has developed a unique culture<br> within the subcontinent, not only with a diverse religious<br> tradition but also with its own language, Malayalam.",
    back_image:
      "linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.8)),url(Images/kerala.jpg)",
    card_image: "url(Images/kerala.jpg)",
  },
  TamilNadu: {
    id: "state-6",
    heading: "Tamil Nadu",
    para: "Tamil Nadu represents the Tamil-speaking area of what<br> was formerly the Madras Presidency of<br> British India. The Tamils are especially proud of<br> their Dravidian language and culture,<br> and they have notably resisted attempts by the<br> central government to make <br>Hindi (an Indo-Aryan language) the sole national language.",
    back_image:
      "linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.8)),url(Images/tamilnadu.jpg)",
    card_image: "url(Images/tamilnadu.jpg)",
  },
  Goa: {
    id: "state-7",
    heading: "Goa",
    para: "Goa, state of India, comprising a mainland district<br> on the country’s southwestern coast and<br> an offshore island. It is located about 250 miles (400 km)<br> south of Mumbai (Bombay).<br> One of India’s smallest states, it is bounded by the states<br> of Maharashtra on the north and Karnataka on the east<br> and south and by the Arabian Sea on the west.",
    back_image:
      "linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.8)),url(Images/goa.jpg)",
    card_image: "url(Images/goa.jpg)",
  },
};

export const heroCards = {
  Maharashtra: {
    Skiing1: {
      id: "sport",
      heading: "Paragliding",
      p: "Paragliding at Kamshet",
      image: "/Adrenaline_junkie/states/Images/sportImages/skiing.jpg",
    },
    Skiing2: {
      id: "sport",
      heading: "White water Rafting",
      p: "White Water Rafting at Kundalika",
      image: "/Adrenaline_junkie/states/Images/sportImages/skiing2.jpg",
      price: "3000",
    },
    paragliding1: {
      id: "sport",
      heading: "Para",
      p: "Para sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/paragliding.jpg",
      price: "4000",
    },
    paragliding2: {
      id: "sport",
      heading: "Para",
      p: "Para sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/paragliding2.jpg",
      price: "5000",
    },
    rockclimbing1: {
      id: "sport",
      heading: "Rock climbing",
      p: "rock sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/rockclimbing.jpg",
      price: "6000",
    },
    rockclimbing2: {
      id: "sport",
      heading: "Rock climbing",
      p: "rock sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/rockclimbing2.jpg",
      price: "7000",
    },
    rockclimbing3: {
      id: "sport",
      heading: "Rock climbing",
      p: "rock sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/rockclimbing.jpg",
      price: "6000",
    },
    rockclimbing4: {
      id: "sport",
      heading: "Rock climbing",
      p: "rock sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/rockclimbing2.jpg",
      price: "7000",
    },
  },
  Telangana: {
    Skiing1: {
      id: "sport",
      heading: "Skiing",
      p: "skiing sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/skiing.jpg",
      price: "2000",
    },
    Skiing2: {
      id: "sport",
      heading: "Skiing",
      p: "skiing sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/skiing2.jpg",
      price: "3000",
    },
    paragliding1: {
      id: "sport",
      heading: "Para",
      p: "Para sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/paragliding.jpg",
      price: "4000",
    },
    paragliding2: {
      id: "sport",
      heading: "Para",
      p: "Para sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/paragliding2.jpg",
      price: "5000",
    },
    rockclimbing1: {
      id: "sport",
      heading: "Rock",
      p: "Rock sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/rockclimbing.jpg",
      price: "6000",
    },
    rockclimbing2: {
      id: "sport",
      heading: "Rock",
      p: "Rock sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/rockclimbing2.jpg",
      price: "7000",
    },
  },
  AndhraPradesh: {
    Skiing1: {
      id: "sport",
      heading: "Skiing",
      p: "skiing sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/skiing.jpg",
      price: "2000",
    },
    Skiing2: {
      id: "sport",
      heading: "Skiing",
      p: "skiing sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/skiing2.jpg",
      price: "3000",
    },
    paragliding1: {
      id: "sport",
      heading: "Para",
      p: "Para sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/paragliding.jpg",
      price: "4000",
    },
    paragliding2: {
      id: "sport",
      heading: "Para",
      p: "Para sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/paragliding2.jpg",
      price: "5000",
    },
    rockclimbing1: {
      id: "sport",
      heading: "Rock climbing",
      p: "Rock sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/rockclimbing.jpg",
      price: "6000",
    },
    rockclimbing2: {
      id: "sport",
      heading: "Rock climbing",
      p: "Rock sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/rockclimbing2.jpg",
      price: "7000",
    },
  },
  Karnataka: {
    Skiing1: {
      id: "sport",
      heading: "Skiing",
      p: "skiing sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/skiing.jpg",
      price: "2000",
    },
    Skiing2: {
      id: "sport",
      heading: "skiing",
      p: "skiing sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/skiing2.jpg",
      price: "3000",
    },
    paragliding1: {
      id: "sport",
      heading: "para",
      p: "para sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/paragliding.jpg",
      price: "4000",
    },
    paragliding2: {
      id: "sport",
      heading: "para",
      p: "para sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/paragliding2.jpg",
      price: "5000",
    },
    rockclimbing1: {
      id: "sport",
      heading: "rock climbing",
      p: "rock sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/rockclimbing.jpg",
      price: "6000",
    },
    rockclimbing2: {
      id: "sport",
      heading: "rock climbing",
      p: "rock sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/rockclimbing2.jpg",
      price: "7000",
    },
  },
  Kerala: {
    Skiing1: {
      id: "sport",
      heading: "Skiing",
      p: "skiing sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/skiing.jpg",
      price: "2000",
    },
    Skiing2: {
      id: "sport",
      heading: "skiing",
      p: "skiing sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/skiing2.jpg",
      price: "3000",
    },
    paragliding1: {
      id: "sport",
      heading: "para",
      p: "para sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/paragliding.jpg",
      price: "4000",
    },
    paragliding2: {
      id: "sport",
      heading: "para",
      p: "para sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/paragliding2.jpg",
      price: "5000",
    },
    rockclimbing1: {
      id: "sport",
      heading: "rock climbing",
      p: "rock sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/rockclimbing.jpg",
      price: "6000",
    },
    rockclimbing2: {
      id: "sport",
      heading: "rock climbing",
      p: "rock sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/rockclimbing2.jpg",
      price: "7000",
    },
  },
  TamilNadu: {
    Skiing1: {
      id: "sport",
      heading: "Skiing",
      p: "skiing sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/skiing.jpg",
      price: "2000",
    },
    Skiing2: {
      id: "sport",
      heading: "skiing",
      p: "skiing sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/skiing2.jpg",
      price: "3000",
    },
    paragliding1: {
      id: "sport",
      heading: "para",
      p: "para sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/paragliding.jpg",
      price: "4000",
    },
    paragliding2: {
      id: "sport",
      heading: "para",
      p: "para sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/paragliding2.jpg",
      price: "5000",
    },
    rockclimbing1: {
      id: "sport",
      heading: "rock climbing",
      p: "rock sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/rockclimbing.jpg",
      price: "6000",
    },
    rockclimbing2: {
      id: "sport",
      heading: "rock climbing",
      p: "rock sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/rockclimbing2.jpg",
      price: "7000",
    },
  },
  Goa: {
    Skiing1: {
      id: "sport",
      heading: "Skiing",
      p: "skiing sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/skiing.jpg",
      price: "2000",
    },
    Skiing2: {
      id: "sport",
      heading: "skiing",
      p: "skiing sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/skiing2.jpg",
      price: "3000",
    },
    paragliding1: {
      id: "sport",
      heading: "para",
      p: "para sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/paragliding.jpg",
      price: "4000",
    },
    paragliding2: {
      id: "sport",
      heading: "para",
      p: "para sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/paragliding2.jpg",
      price: "5000",
    },
    rockclimbing1: {
      id: "sport",
      heading: "rock climbing",
      p: "rock sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/rockclimbing.jpg",
      price: "6000",
    },
    rockclimbing2: {
      id: "sport",
      heading: "rock climbing",
      p: "rock sport",
      image: "/Adrenaline_junkie/states/Images/sportImages/rockclimbing2.jpg",
      price: "7000",
    },
  },
};
